@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Dec 12 13:11:43 +0100 2021
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim dice_tb_behav -key {Behavioral:sim_1:Functional:dice_tb} -tclbatch dice_tb.tcl -view C:/Users/timim/OneDrive - FH JOANNEUM/1STM/Digital_Electronics/Lab5_Dice/Proj_Lab5/dice_project/dice_tb_behav.wcfg -log simulate.log"
call xsim  dice_tb_behav -key {Behavioral:sim_1:Functional:dice_tb} -tclbatch dice_tb.tcl -view C:/Users/timim/OneDrive - FH JOANNEUM/1STM/Digital_Electronics/Lab5_Dice/Proj_Lab5/dice_project/dice_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
